modLoader="javafml"
loaderVersion="[4,)"
license="${mod_license}"
issueTrackerURL="${issues_url}"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    displayURL="${mod_url}"
    iconFile="assets/freezeframe/icon.png"
    authors="Lunade/AViewFromTheTop, Lufurrius"
    description='''
Adds Cameras to Minecraft in an intuitive and vanilla way.
    '''

[[mixins]]
config="freezeframe.mixins.json"

[[mixins]]
config="freezeframe.neoforge.mixins.json"

[[ dependencies.freezeframe ]]
    modId="neoforge"
    type="required"
    versionRange="[${minecraft_version},)"
    ordering="NONE"
    side="BOTH"

[[ dependencies.freezeframe ]]
    modId="minecraft"
    type="required"
    versionRange="[${minecraft_version},)"
    ordering="NONE"
    side="BOTH"

[[ dependencies.freezeframe ]]
    modId="frozenlib"
    type="required"
    versionRange="[${frozenlib_version},)"
    ordering="NONE"
    side="BOTH"

[[ dependencies.freezeframe ]]
    modId="cloth-config"
    type="optional"
    versionRange="*"
    ordering="NONE"
    side="BOTH"
